CC =gcc
CXX =g++
CXXFLAGS =-g -Wall --std=c++11

EXECUTE = entry.cpp server2.cpp socket_utilities.cpp string_utilities.cpp buffer_content.cpp

execute: $(EXECUTE)
	$(CXX) $(GXXFLAGS) -o server2 $(EXECUTE)
